POST http://localhost:5050/v1/messages
Content-Type: application/json

{
  "message": "Olá chat, retorne uma mensagem para eu saber se meu codigo deu certo",
  "context_id": "0a50e0d6-079b-4960-9323-e6e38ed5929a"

}
